---
name: Context-Handle
version: 0.01
author:
  - 'Yuval Kogman <nothingmuch@woobling.org>'
abstract: A convenient context propagation proxy thingy.
license: perl
requires:
  Want: 0.10
  ok: 0
  perl: 5.6.1
provides:
  Context::Handle:
    file: lib/Context/Handle.pm
    version: 0.01
  Context::Handle::RV::Bool:
    file: lib/Context/Handle/RV/Bool.pm
  Context::Handle::RV::List:
    file: lib/Context/Handle/RV/List.pm
  Context::Handle::RV::RefArray:
    file: lib/Context/Handle/RV/RefArray.pm
  Context::Handle::RV::RefCode:
    file: lib/Context/Handle/RV/RefCode.pm
  Context::Handle::RV::RefHash:
    file: lib/Context/Handle/RV/RefHash.pm
  Context::Handle::RV::RefObject:
    file: lib/Context/Handle/RV/RefObject.pm
  Context::Handle::RV::RefScalar:
    file: lib/Context/Handle/RV/RefScalar.pm
  Context::Handle::RV::Scalar:
    file: lib/Context/Handle/RV/Scalar.pm
  Context::Handle::RV::Void:
    file: lib/Context/Handle/RV/Void.pm
generated_by: Module::Build version 0.2611
